//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jvedio.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jvedio.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似         Jvedio 是本地视频管理软件，支持扫描本地视频并导入软件，建立视频库， 提取出视频的 唯一识别码，自动分类视频， 添加标签管理视频，使用人工智能识别演员，支持翻译信息， 基于 FFmpeg 截取视频图片，Window 桌面端流畅美观的应用软件 的本地化字符串。
        /// </summary>
        public static string About_Content {
            get {
                return ResourceManager.GetString("About_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地视频的管理 的本地化字符串。
        /// </summary>
        public static string About_Outline {
            get {
                return ResourceManager.GetString("About_Outline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 演员 的本地化字符串。
        /// </summary>
        public static string Actor {
            get {
                return ResourceManager.GetString("Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄 的本地化字符串。
        /// </summary>
        public static string Actress_Age {
            get {
                return ResourceManager.GetString("Actress_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生日 的本地化字符串。
        /// </summary>
        public static string Actress_Birthday {
            get {
                return ResourceManager.GetString("Actress_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生地 的本地化字符串。
        /// </summary>
        public static string Actress_Birthplace {
            get {
                return ResourceManager.GetString("Actress_Birthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胸围 的本地化字符串。
        /// </summary>
        public static string Actress_Chest {
            get {
                return ResourceManager.GetString("Actress_Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罩杯 的本地化字符串。
        /// </summary>
        public static string Actress_Cup {
            get {
                return ResourceManager.GetString("Actress_Cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身高 的本地化字符串。
        /// </summary>
        public static string Actress_Height {
            get {
                return ResourceManager.GetString("Actress_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 臀围 的本地化字符串。
        /// </summary>
        public static string Actress_Hipline {
            get {
                return ResourceManager.GetString("Actress_Hipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱好 的本地化字符串。
        /// </summary>
        public static string Actress_Hobby {
            get {
                return ResourceManager.GetString("Actress_Hobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 腰围 的本地化字符串。
        /// </summary>
        public static string Actress_Waist {
            get {
                return ResourceManager.GetString("Actress_Waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 头像 的本地化字符串。
        /// </summary>
        public static string ActressImage {
            get {
                return ResourceManager.GetString("ActressImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有视频 的本地化字符串。
        /// </summary>
        public static string AllVideo {
            get {
                return ResourceManager.GetString("AllVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能分类 的本地化字符串。
        /// </summary>
        public static string AutoClassification {
            get {
                return ResourceManager.GetString("AutoClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批处理 的本地化字符串。
        /// </summary>
        public static string BatchProcessing {
            get {
                return ResourceManager.GetString("BatchProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速添加+ 的本地化字符串。
        /// </summary>
        public static string FastImport {
            get {
                return ResourceManager.GetString("FastImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特別收藏 的本地化字符串。
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈 的本地化字符串。
        /// </summary>
        public static string FeedBack {
            get {
                return ResourceManager.GetString("FeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别码 的本地化字符串。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片类型 的本地化字符串。
        /// </summary>
        public static string ImageType {
            get {
                return ResourceManager.GetString("ImageType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入需添加的标签，每个标签空格隔开 的本地化字符串。
        /// </summary>
        public static string InputTitle1 {
            get {
                return ResourceManager.GetString("InputTitle1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入需要同步的影片网址 的本地化字符串。
        /// </summary>
        public static string InputTitle2 {
            get {
                return ResourceManager.GetString("InputTitle2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入修改的名称 的本地化字符串。
        /// </summary>
        public static string InputTitle3 {
            get {
                return ResourceManager.GetString("InputTitle3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入你要添加的清单 的本地化字符串。
        /// </summary>
        public static string InputTitle4 {
            get {
                return ResourceManager.GetString("InputTitle4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入需添加的识别码 的本地化字符串。
        /// </summary>
        public static string InputTitle5 {
            get {
                return ResourceManager.GetString("InputTitle5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请输入需删除的标签，每个标签空格隔开 的本地化字符串。
        /// </summary>
        public static string InputTitle6 {
            get {
                return ResourceManager.GetString("InputTitle6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 加入清单 的本地化字符串。
        /// </summary>
        public static string Menu_AddToList {
            get {
                return ResourceManager.GetString("Menu_AddToList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扩展功能 的本地化字符串。
        /// </summary>
        public static string Menu_Advance {
            get {
                return ResourceManager.GetString("Menu_Advance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空信息 的本地化字符串。
        /// </summary>
        public static string Menu_ClearInfo {
            get {
                return ResourceManager.GetString("Menu_ClearInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制文件(C) 的本地化字符串。
        /// </summary>
        public static string Menu_CopyFile {
            get {
                return ResourceManager.GetString("Menu_CopyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定网址 的本地化字符串。
        /// </summary>
        public static string Menu_CustomUrl {
            get {
                return ResourceManager.GetString("Menu_CustomUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件(T) 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteFile {
            get {
                return ResourceManager.GetString("Menu_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除信息(D) 的本地化字符串。
        /// </summary>
        public static string Menu_DeleteInfo {
            get {
                return ResourceManager.GetString("Menu_DeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改信息(E) 的本地化字符串。
        /// </summary>
        public static string Menu_EditInfo {
            get {
                return ResourceManager.GetString("Menu_EditInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 强制同步 的本地化字符串。
        /// </summary>
        public static string Menu_EnforceSync {
            get {
                return ResourceManager.GetString("Menu_EnforceSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成演员头像 的本地化字符串。
        /// </summary>
        public static string Menu_GenerateActressImage {
            get {
                return ResourceManager.GetString("Menu_GenerateActressImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成 Gif 的本地化字符串。
        /// </summary>
        public static string Menu_GenerateGif {
            get {
                return ResourceManager.GetString("Menu_GenerateGif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成截图 的本地化字符串。
        /// </summary>
        public static string Menu_GenerateScreenShot {
            get {
                return ResourceManager.GetString("Menu_GenerateScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生成缩略图 的本地化字符串。
        /// </summary>
        public static string Menu_GenerateThumbnail {
            get {
                return ResourceManager.GetString("Menu_GenerateThumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 添加已有的标签 的本地化字符串。
        /// </summary>
        public static string Menu_LabelManage1 {
            get {
                return ResourceManager.GetString("Menu_LabelManage1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单影片修改标签 的本地化字符串。
        /// </summary>
        public static string Menu_LabelManage2 {
            get {
                return ResourceManager.GetString("Menu_LabelManage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多影片添加标签 的本地化字符串。
        /// </summary>
        public static string Menu_LabelManage3 {
            get {
                return ResourceManager.GetString("Menu_LabelManage3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多影片删除标签 的本地化字符串。
        /// </summary>
        public static string Menu_LabelManage4 {
            get {
                return ResourceManager.GetString("Menu_LabelManage4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多影片清空标签 的本地化字符串。
        /// </summary>
        public static string Menu_LabelManage5 {
            get {
                return ResourceManager.GetString("Menu_LabelManage5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标签管理 的本地化字符串。
        /// </summary>
        public static string Menu_LabelManagement {
            get {
                return ResourceManager.GetString("Menu_LabelManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开网址(W) 的本地化字符串。
        /// </summary>
        public static string Menu_OpenWebSite {
            get {
                return ResourceManager.GetString("Menu_OpenWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 移出清单 的本地化字符串。
        /// </summary>
        public static string Menu_RemoveFromList {
            get {
                return ResourceManager.GetString("Menu_RemoveFromList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 去 5 位数字的前2个0 的本地化字符串。
        /// </summary>
        public static string Menu_RemoveZero {
            get {
                return ResourceManager.GetString("Menu_RemoveZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名影片 的本地化字符串。
        /// </summary>
        public static string Menu_RenameFile {
            get {
                return ResourceManager.GetString("Menu_RenameFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 高级同步 的本地化字符串。
        /// </summary>
        public static string Menu_SyncExtra {
            get {
                return ResourceManager.GetString("Menu_SyncExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 立即同步(S) 的本地化字符串。
        /// </summary>
        public static string Menu_SyncInfo {
            get {
                return ResourceManager.GetString("Menu_SyncInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 翻译标题和摘要 的本地化字符串。
        /// </summary>
        public static string Menu_Translate {
            get {
                return ResourceManager.GetString("Menu_Translate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影片 的本地化字符串。
        /// </summary>
        public static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出演人员 的本地化字符串。
        /// </summary>
        public static string MovieActors {
            get {
                return ResourceManager.GetString("MovieActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影片类别 的本地化字符串。
        /// </summary>
        public static string MovieGenre {
            get {
                return ResourceManager.GetString("MovieGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影片标签 的本地化字符串。
        /// </summary>
        public static string MovieLabels {
            get {
                return ResourceManager.GetString("MovieLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影视库 的本地化字符串。
        /// </summary>
        public static string MovieManagement {
            get {
                return ResourceManager.GetString("MovieManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影片评分 的本地化字符串。
        /// </summary>
        public static string MovieRating {
            get {
                return ResourceManager.GetString("MovieRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 多选模式 的本地化字符串。
        /// </summary>
        public static string MultiSelect {
            get {
                return ResourceManager.GetString("MultiSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的清单 的本地化字符串。
        /// </summary>
        public static string MyList {
            get {
                return ResourceManager.GetString("MyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官方网址 的本地化字符串。
        /// </summary>
        public static string OfficialWebsite {
            get {
                return ResourceManager.GetString("OfficialWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开位置 的本地化字符串。
        /// </summary>
        public static string OpenPath {
            get {
                return ResourceManager.GetString("OpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海报图 的本地化字符串。
        /// </summary>
        public static string Poster {
            get {
                return ResourceManager.GetString("Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览图 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        public static string Raname {
            get {
                return ResourceManager.GetString("Raname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近创建 的本地化字符串。
        /// </summary>
        public static string RecentCreate {
            get {
                return ResourceManager.GetString("RecentCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近播放 的本地化字符串。
        /// </summary>
        public static string RecentPlay {
            get {
                return ResourceManager.GetString("RecentPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发行年份 的本地化字符串。
        /// </summary>
        public static string ReleaseYear {
            get {
                return ResourceManager.GetString("ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影片截图 的本地化字符串。
        /// </summary>
        public static string ScreenShot {
            get {
                return ResourceManager.GetString("ScreenShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再检索 的本地化字符串。
        /// </summary>
        public static string SearchCurrent {
            get {
                return ResourceManager.GetString("SearchCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 识别码、演员、名称 的本地化字符串。
        /// </summary>
        public static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示全部 的本地化字符串。
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件目录 的本地化字符串。
        /// </summary>
        public static string SoftWare {
            get {
                return ResourceManager.GetString("SoftWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 排序 的本地化字符串。
        /// </summary>
        public static string Sorting {
            get {
                return ResourceManager.GetString("Sorting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 停止同步 的本地化字符串。
        /// </summary>
        public static string StopSync {
            get {
                return ResourceManager.GetString("StopSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 同步信息 的本地化字符串。
        /// </summary>
        public static string SyncInfo {
            get {
                return ResourceManager.GetString("SyncInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鸣谢 的本地化字符串。
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 感谢 众多网友对 Jvedio 的赞助与支持！ 的本地化字符串。
        /// </summary>
        public static string Thanks_Content1 {
            get {
                return ResourceManager.GetString("Thanks_Content1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预祝 Jvedio 发展越来越好！ 的本地化字符串。
        /// </summary>
        public static string Thanks_Content2 {
            get {
                return ResourceManager.GetString("Thanks_Content2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩略图 的本地化字符串。
        /// </summary>
        public static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清空同步的信息 的本地化字符串。
        /// </summary>
        public static string ToolTip_ClearInfo {
            get {
                return ResourceManager.GetString("ToolTip_ClearInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除文件到回收站 的本地化字符串。
        /// </summary>
        public static string ToolTip_DeleteFile {
            get {
                return ResourceManager.GetString("ToolTip_DeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除信息（不删除文件） 的本地化字符串。
        /// </summary>
        public static string ToolTip_DeleteInfo {
            get {
                return ResourceManager.GetString("ToolTip_DeleteInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 组合筛选 的本地化字符串。
        /// </summary>
        public static string ToolTip_Filter {
            get {
                return ResourceManager.GetString("ToolTip_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 随机展示 的本地化字符串。
        /// </summary>
        public static string ToolTip_RandomShow {
            get {
                return ResourceManager.GetString("ToolTip_RandomShow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级 的本地化字符串。
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频时长 的本地化字符串。
        /// </summary>
        public static string VedioDuration {
            get {
                return ResourceManager.GetString("VedioDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频类型 的本地化字符串。
        /// </summary>
        public static string VedioType {
            get {
                return ResourceManager.GetString("VedioType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 版本 的本地化字符串。
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官网 的本地化字符串。
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按演员 的本地化字符串。
        /// </summary>
        public static string WithActress {
            get {
                return ResourceManager.GetString("WithActress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按类别 的本地化字符串。
        /// </summary>
        public static string WithGenre {
            get {
                return ResourceManager.GetString("WithGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按标签 的本地化字符串。
        /// </summary>
        public static string WithLabel {
            get {
                return ResourceManager.GetString("WithLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按路径 的本地化字符串。
        /// </summary>
        public static string WithPath {
            get {
                return ResourceManager.GetString("WithPath", resourceCulture);
            }
        }
    }
}
