//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jvedio.Language {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jvedio.Language.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 关于 的本地化字符串。
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 演员 的本地化字符串。
        /// </summary>
        public static string Actor {
            get {
                return ResourceManager.GetString("Actor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 年龄 的本地化字符串。
        /// </summary>
        public static string Actress_Age {
            get {
                return ResourceManager.GetString("Actress_Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 生日 的本地化字符串。
        /// </summary>
        public static string Actress_Birthday {
            get {
                return ResourceManager.GetString("Actress_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出生地 的本地化字符串。
        /// </summary>
        public static string Actress_Birthplace {
            get {
                return ResourceManager.GetString("Actress_Birthplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 胸围 的本地化字符串。
        /// </summary>
        public static string Actress_Chest {
            get {
                return ResourceManager.GetString("Actress_Chest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 罩杯 的本地化字符串。
        /// </summary>
        public static string Actress_Cup {
            get {
                return ResourceManager.GetString("Actress_Cup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身高 的本地化字符串。
        /// </summary>
        public static string Actress_Height {
            get {
                return ResourceManager.GetString("Actress_Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 臀围 的本地化字符串。
        /// </summary>
        public static string Actress_Hipline {
            get {
                return ResourceManager.GetString("Actress_Hipline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 爱好 的本地化字符串。
        /// </summary>
        public static string Actress_Hobby {
            get {
                return ResourceManager.GetString("Actress_Hobby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 腰围 的本地化字符串。
        /// </summary>
        public static string Actress_Waist {
            get {
                return ResourceManager.GetString("Actress_Waist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有视频 的本地化字符串。
        /// </summary>
        public static string AllVideo {
            get {
                return ResourceManager.GetString("AllVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 应用 的本地化字符串。
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 智能分类 的本地化字符串。
        /// </summary>
        public static string AutoClassification {
            get {
                return ResourceManager.GetString("AutoClassification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 批处理 的本地化字符串。
        /// </summary>
        public static string BatchProcessing {
            get {
                return ResourceManager.GetString("BatchProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 清除 的本地化字符串。
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 快速添加+ 的本地化字符串。
        /// </summary>
        public static string FastImport {
            get {
                return ResourceManager.GetString("FastImport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 特別收藏 的本地化字符串。
        /// </summary>
        public static string Favorites {
            get {
                return ResourceManager.GetString("Favorites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈 的本地化字符串。
        /// </summary>
        public static string FeedBack {
            get {
                return ResourceManager.GetString("FeedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件大小 的本地化字符串。
        /// </summary>
        public static string FileSize {
            get {
                return ResourceManager.GetString("FileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 帮助 的本地化字符串。
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 识别码 的本地化字符串。
        /// </summary>
        public static string ID {
            get {
                return ResourceManager.GetString("ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 日志 的本地化字符串。
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出演人员 的本地化字符串。
        /// </summary>
        public static string MovieActors {
            get {
                return ResourceManager.GetString("MovieActors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影片类别 的本地化字符串。
        /// </summary>
        public static string MovieGenre {
            get {
                return ResourceManager.GetString("MovieGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影片标签 的本地化字符串。
        /// </summary>
        public static string MovieLabels {
            get {
                return ResourceManager.GetString("MovieLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影视库 的本地化字符串。
        /// </summary>
        public static string MovieManagement {
            get {
                return ResourceManager.GetString("MovieManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 影片评分 的本地化字符串。
        /// </summary>
        public static string MovieRating {
            get {
                return ResourceManager.GetString("MovieRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 我的清单 的本地化字符串。
        /// </summary>
        public static string MyList {
            get {
                return ResourceManager.GetString("MyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开位置 的本地化字符串。
        /// </summary>
        public static string OpenPath {
            get {
                return ResourceManager.GetString("OpenPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 海报图 的本地化字符串。
        /// </summary>
        public static string Poster {
            get {
                return ResourceManager.GetString("Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预览图 的本地化字符串。
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 重命名 的本地化字符串。
        /// </summary>
        public static string Raname {
            get {
                return ResourceManager.GetString("Raname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近创建 的本地化字符串。
        /// </summary>
        public static string RecentCreate {
            get {
                return ResourceManager.GetString("RecentCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 最近播放 的本地化字符串。
        /// </summary>
        public static string RecentPlay {
            get {
                return ResourceManager.GetString("RecentPlay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发行年份 的本地化字符串。
        /// </summary>
        public static string ReleaseYear {
            get {
                return ResourceManager.GetString("ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 再检索 的本地化字符串。
        /// </summary>
        public static string SearchCurrent {
            get {
                return ResourceManager.GetString("SearchCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 搜索 识别码、演员、名称 的本地化字符串。
        /// </summary>
        public static string SearchHint {
            get {
                return ResourceManager.GetString("SearchHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示 的本地化字符串。
        /// </summary>
        public static string Show {
            get {
                return ResourceManager.GetString("Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示全部 的本地化字符串。
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 软件目录 的本地化字符串。
        /// </summary>
        public static string SoftWare {
            get {
                return ResourceManager.GetString("SoftWare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 鸣谢 的本地化字符串。
        /// </summary>
        public static string Thanks {
            get {
                return ResourceManager.GetString("Thanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 缩略图 的本地化字符串。
        /// </summary>
        public static string Thumbnail {
            get {
                return ResourceManager.GetString("Thumbnail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工具 的本地化字符串。
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 升级 的本地化字符串。
        /// </summary>
        public static string Upgrade {
            get {
                return ResourceManager.GetString("Upgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频时长 的本地化字符串。
        /// </summary>
        public static string VedioDuration {
            get {
                return ResourceManager.GetString("VedioDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 视频类型 的本地化字符串。
        /// </summary>
        public static string VedioType {
            get {
                return ResourceManager.GetString("VedioType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 官网 的本地化字符串。
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按演员 的本地化字符串。
        /// </summary>
        public static string WithActress {
            get {
                return ResourceManager.GetString("WithActress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按类别 的本地化字符串。
        /// </summary>
        public static string WithGenre {
            get {
                return ResourceManager.GetString("WithGenre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按标签 的本地化字符串。
        /// </summary>
        public static string WithLabel {
            get {
                return ResourceManager.GetString("WithLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 按路径 的本地化字符串。
        /// </summary>
        public static string WithPath {
            get {
                return ResourceManager.GetString("WithPath", resourceCulture);
            }
        }
    }
}
